name: Tests

on: push

defaults:
  run:
    working-directory: .

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Node.js modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: dependencies-node-npm-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Run Jest
        run: npm run test -- --verbose
